### ISSUE TITLE
Respect erc-fill-prefix

### ISSUE THREAD

**Issue by dieggsy** [kidd/erc-image.el#22]
Would be nice if images could be aligned to this

**Comment by dieggsy** [comment]
All this really requires is putting `erc-fill-prefix` in the last call to `insert-before-markers`, potentially making this behavior optional through a defcustom. I could PR if you wish.

**Comment by kidd** [comment]
Hello diego, 
I still learn one or two emacs variables each week :).

I'm pushing an update that respects `(or erc-fill-prefix "")`, which should do the job.  I don't think it makes sense to add a defcustom for that (too many configuration points already, and I think it makes sense to just obey erc-fill-prefix)

**Comment by dieggsy** [comment]
@kidd  oh, `or` is a _solid_ way to do this, hah. thanks!
